### ISSUE TITLE
パスワード変更時にバリデーションエラーが適用されません

### ISSUE THREAD

**Issue by rook1202** [rook1202/runteq_graduation_productio-#65]
## 解決したいこと・達成したいものについて
パスワード変更自体はできるようになっています。
ただ新しいパスワードが空欄、もしくはバリデーションで指定している6字以下のパスワードでもバリデーションエラーにならず成功となってしまいます。
その場合、新しいパスワード、前のパスワード両方使用できず、ログインができなくなります。
エラーが働くようにしたいです。

## 聞きたいこと・アドバイスが欲しいこと
password_resets_controller.rbのupdateアクションかUserモデルのバリデーションの記述が間違っているのでしょうか？
それともコントローラーで別途チェックをした方がいいのでしょうか？

## 実装の際に参考にした資料等
RUNTEQの課題
ChatGPT

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
app/models/user.rb
```ruby
class User < ApplicationRecord
  authenticates_with_sorcery!

  has_many :partners, foreign_key: :owner_id,
                      dependent: :destroy, inverse_of: :owner

  # バリデーションを追加
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true
end
``` 
app/controller/password_resets_controller.rb
```ruby
def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)
    if @user.blank?
      flash[:danger] = '無効なパスワードリセットリンクです。'
      redirect_to new_password_reset_path
      return
    end

      # Sorceryのパスワード変更メソッドの前に直接属性を設定
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation]

      if @user.change_password(params[:user][:password])
        flash[:success] = 'パスワードが変更されました。'
        redirect_to login_path
      else
        flash.now[:danger] = 'パスワードの変更ができませんでした。'
        render :edit
      end
  end
``` 
app/views/password_resets/edit.html.erb
```ruby
<% @page_title = "パスワード再設定" %>

<div class="container mt-5">
  <div class="row">
    <div class="col-11 col-md-6 mx-auto">
    <%= render 'shared/error_messages', object: @user %>

        <p>新しいパスワードを入力してパスワード変更ボタンを押してください。</p>

        <div class="border col-12 rounded p-5 mx-auto">

        <%= form_with model: @user, url: password_reset_path(params[:id]), local: true do |f| %>
            <div class="mb-3">
            <%= f.label :password, "新しいパスワード", class: "form-label" %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.label :password_confirmation, "パスワード確認", class: "form-label" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
            </div>

            <%= f.submit 'パスワード変更', class: 'btn btn-custom w-100' %>
        <% end %>
        </div>
    </div>
  </div>
</div>
``` 
## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
password_resets_controller.rbのupdateアクションかUserモデルのバリデーションの記述でしょうか。

## 検証した結果から分かったこと・考えたこと
```ruby
def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)
    if @user.blank?
      flash[:danger] = '無効なパスワードリセットリンクです。'
      redirect_to new_password_reset_path
      return
    end

      # Sorceryのパスワード変更メソッドの前に直接属性を設定
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation]

      # バリデーションチェックの内容を出力
      check_validations(@user)
      
    if @user.valid? # バリデーションを手動でチェック
      if @user.change_password(params[:user][:password])
        flash[:success] = 'パスワードが変更されました。'
        redirect_to login_path
      else
         puts "change_passwordでのエラー: #{@user.errors.full_messages}"
        flash.now[:danger] = 'パスワードの変更ができませんでした。'
        render :edit
      end
    end
  end

  private
def check_validations(user)
    puts "=== バリデーションチェック ==="
    user.class.validators.each do |validator|
      puts "チェック内容: #{validator.attributes} - #{validator.options}"
      validator.attributes.each do |attribute|
        if user.errors[attribute].empty?
          puts "  - #{attribute}: OK"
        else
          puts "  - #{attribute}: NG (#{user.errors[attribute].join(', ')})"
        end
      end
    end
    puts "==========================="
  end
``` 
この状態で変更を実行すると以下のように出力されます。
```
web-1     | Started PATCH "/password_resets/xxwmc_Zbi_vrXUY4_xWZ" for 172.18.0.1 at 2024-11-26 11:05:01 +0900
web-1     | Cannot render console from 172.18.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1
web-1     | Processing by PasswordResetsController#update as TURBO_STREAM
web-1     |   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"パスワード変更", "id"=>"xxwmc_Zbi_vrXUY4_xWZ"}
web-1     |   User Load (0.5ms)  SELECT `users`.* FROM `users` WHERE `users`.`reset_password_token` = 'xxwmc_Zbi_vrXUY4_xWZ' ORDER BY `users`.`id` ASC LIMIT 1
web-1     |   ↳ app/controllers/password_resets_controller.rb:32:in `update'
web-1     | === バリデーションチェック ===
web-1     | チェック内容: [:name] - {}
web-1     |   - name: OK
web-1     | チェック内容: [:email] - {}
web-1     |   - email: OK
web-1     | チェック内容: [:email] - {}
web-1     |   - email: OK
web-1     | チェック内容: [:password] - {:if=>#<Proc:0x00007fa645683d30 /runteq_graduation_productio-/app/models/user.rb:13 (lambda)>, :minimum=>6}
web-1     |   - password: OK
web-1     | チェック内容: [:password] - {:case_sensitive=>true, :if=>#<Proc:0x00007fa645682ea8 /runteq_graduation_productio-/app/models/user.rb:14 (lambda)>}
web-1     |   - password: OK
web-1     | チェック内容: [:password_confirmation] - {:if=>#<Proc:0x00007fa645681940 /runteq_graduation_productio-/app/models/user.rb:15 (lambda)>}
web-1     |   - password_confirmation: OK
web-1     | チェック内容: [:reset_password_token] - {:allow_nil=>true}
web-1     |   - reset_password_token: OK
web-1     | ===========================
web-1     |   User Exists? (0.6ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = 'runteq@example.com' AND `users`.`id` != 1 LIMIT 1
web-1     |   ↳ app/controllers/password_resets_controller.rb:46:in `update'
web-1     |   User Exists? (0.4ms)  SELECT 1 AS one FROM `users` WHERE `users`.`reset_password_token` = 'xxwmc_Zbi_vrXUY4_xWZ' AND `users`.`id` != 1 LIMIT 1
web-1     |   ↳ app/controllers/password_resets_controller.rb:46:in `update'
web-1     |   CACHE User Exists? (0.0ms)  SELECT 1 AS one FROM `users` WHERE `users`.`email` = 'runteq@example.com' AND `users`.`id` != 1 LIMIT 1
web-1     |   ↳ app/controllers/password_resets_controller.rb:47:in `update'
web-1     |   TRANSACTION (0.2ms)  BEGIN
web-1     |   ↳ app/controllers/password_resets_controller.rb:47:in `update'
web-1     |   User Update (0.6ms)  UPDATE `users` SET `users`.`updated_at` = '2024-11-26 02:05:01.245472', `users`.`reset_password_token` = NULL WHERE `users`.`id` = 1
web-1     |   ↳ app/controllers/password_resets_controller.rb:47:in `update'
web-1     |   TRANSACTION (3.7ms)  COMMIT
web-1     |   ↳ app/controllers/password_resets_controller.rb:47:in `update'
web-1     | Redirected to http://localhost:3000/login
web-1     | Completed 302 Found in 20ms (ActiveRecord: 6.1ms | Allocations: 5692)
``` 
ユーザーモデルへの保存自体はできる（6字以上でパスワードを入力した場合変更されている）ため、Userテーブルに保存処理がされているのですが、その際にバリデーションがうまく働かず、スルーしてしまいます。

他、ChatGPTで確認し試してみたこと
モデルのバリデーションのchanges[:crypted_password]の部分をpassword.present?として明示的にする
→変化なし
@user.change_password(params[:user][:password])を@user.saveにする
→変化なし
こちらに関してはsorceryの問題を疑ったのですが結局バリデーションチェック自体は動いていたため関係ないと考えもとに戻しています。

**Comment by kenchasonakai** [comment]
原因わかりませんが、見るなら

`validates :password, length: { minimum: 6 }, if: -> { new_record? || changes[:crypted_password] }`

ここの一文でifオプションを使って`new_record?`なのか、`changes[:crypted_password]`に当てはまるときのみバリデーションを実行するようになっているので、change_passwordメソッドを実行するコードの前で`@user`がどちらかの条件に当てはまるか見てみる感じが良いのかなと思います

細かいところなので時間がかかりそうであれば機能の実装を優先で先に進めてしまって後ほど着手する感じでもよいかなと思います
